global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:2112']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:2113'] 